apiVersion: v1
kind: Service
metadata:
  name: cpa-dev
spec:
  selector:
    app: cpa-dev
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007 # Ignore since we port forward in cluster and dev
